[package]
name = "wash"
version = "0.0.1"
authors = ["Richard Anaya"]
edition = "2018"
description = "an interactive shell for web assembly"
license = "MIT"

[lib]
crate-type =["cdylib"]

[dependencies]
web-dom = "0.1.3"
joss = "0"
ref_thread_local = "0.0"
serde_derive="1"
serde="1"
serde_json="1"
