[package]
name = "wash"
version = "0.0.0"
authors = ["Richard Anaya"]
edition = "2018"
description = "an interactive shell for web assembly"
license = "MIT"

[lib]
crate-type =["cdylib"]

[dependencies]
web-dom = "0.0.14"
